apiVersion: v2
appVersion: "1.3.0"
description: Zeebe Full Helm chart, which comes with Zeebe Cluster, Operate and Tasklist Helm Chart for Kubernetes.
name: zeebe-full-helm
version: 1.3.0
type: application
icon: https://helm.camunda.io/imgs/zeebe-logo.png
dependencies:
- name: zeebe-cluster-helm
  repository: https://camunda-community-hub.github.io/camunda-cloud-helm/
  version: 1.3.1
- name: zeebe-operate-helm
  repository: https://camunda-community-hub.github.io/camunda-cloud-helm/
  version: 1.3.0
- condition: tasklist.enabled
  name: zeebe-tasklist-helm
  repository: https://camunda-community-hub.github.io/camunda-cloud-helm/
  version: 1.3.0
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.15
annotations:
  artifacthub.io/changes: |
    - bump operate chart version to 1.3.0
    - bump tasklist chart version to 1.3.0
    - bump cluster chart version to 1.3.1
  artifacthub.io/containsSecurityUpdates: "true"
